### ISSUE TITLE
Document defaults for CallOptions

### ISSUE THREAD

**Issue by vsubramani** [googleapis/gax-python#106]
During the usability study, participants intuitively understood the role of the CallOptions parameter, and its implications on their API requests.

However, for those that investigated further, it was not clear what the default CallOptions setting were, and thus it was difficult to predict the behavior of their requests without first manually setting the options.

**Recommendation:** Ensure that default CallOptions are accurately and clearly documented. If default options differ by API request, consider adding the defaults to each method’s reference documentation, so user can accurately predict the behavior of their request.

/cc @rok987 
/cc @andrewmacvean
/cc @tbetbetbe

**Comment by geigerj** [comment]
Note, this is the same as googleapis/toolkit#197

**Comment by bjwatson** [comment]
https://github.com/googleapis/toolkit/issues/197 is tracking this issue.
