### ISSUE TITLE
Bundling: handle limits

### ISSUE THREAD

**Issue by geigerj** [googleapis/gax-python#119]
The current bundling config specifies limits, in addition to thresholds. These are currently ignored, but should be implemented. See https://github.com/googleapis/toolkit/blob/3b60c778b59635c97d9a8db2582cf6f84c9ee7fa/src/main/proto/com/google/api/codegen/config.proto#L272

**Comment by bjwatson** [comment]
Hold off until we determine what to do with bundling.
