### ISSUE TITLE
Remove `beta` from gRPC imports

### ISSUE THREAD

**Issue by bjwatson** [googleapis/gax-python#126]
### What:
Change imports of `grpc.beta...` to `grpc...`.

### Why:
gRPC is almost GA, and gcloud has already made this change: https://github.com/GoogleCloudPlatform/gcloud-python/pull/2149

**Comment by dhermes** [comment]
Thanks for filing @bjwatson. There were a few hairy parts that weren't just renames, e.g. `grpc.secure_channel` takes `('host:port', channel_creds)` while `grpc.beta.implementations.secure_channel` takes `(host, port, channel_credentials)` (though the beta implementation calls the stable one).

**Comment by geigerj** [comment]
@dhermes Thanks for the heads-up on `grpc.secure_channel`. From the grpc source code, it looks like all other `grpc.beta` functions that we currently depend on are currently actually implemented as aliases to their non-beta equivalents, so should be pretty easy.

**Comment by dhermes** [comment]
Sure thing. I did a lot of `grpc.foo is grpc.beta.foo` and was pretty happy to find the same thing

**Comment by geigerj** [comment]
Status update: changing GAX requires updating generated code, which itself requires changing our tooling to use `grpcio-tools` instead of `protoc` + `grpc_python_plugin`. That change is waiting on a workaround to https://github.com/grpc/grpc/issues/7857.
