### ISSUE TITLE
Add support for Python 3.6

### ISSUE THREAD

**Issue by bjwatson** [googleapis/gax-python#143]
### What
Add Travis CI rule for testing `gax-python` and generated GAPIC code against Python 3.6.

### Why
The [google-cloud-python project](https://github.com/GoogleCloudPlatform/google-cloud-python) is [about to support 3.6](https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2902).

AppVeyor and Travis might not support 3.6 yet, so we might delay on fixing this issue as a result.

**Comment by lukesneeringer** [comment]
I was just about to bring this up. :-)

**Comment by lukesneeringer** [comment]
This has been done.
