### ISSUE TITLE
Broken getting the VERSION

### ISSUE THREAD

**Issue by delfick** [googleapis/gax-python#152]
Hello,

As per my comment here https://github.com/googleapis/gax-python/commit/5f38e2f68a24dd8540f46d1ab27a10a29a8af2fb#commitcomment-20671765

Thanks

Stephen

**Comment by chmeyers** [comment]
+1

**Comment by geigerj** [comment]
We've rolled this change back and released 0.15.3. Sorry for the breakage. :(

**Comment by delfick** [comment]
Excellent. Thanks
