### ISSUE TITLE
0.15.5 BROKEN?

### ISSUE THREAD

**Issue by tcroiset** [googleapis/gax-python#158]
At least, google-cloud-pubsub doesn't work anymore with it:

16:54:55.000 File "/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub/topic.py", line 249, in publish
16:54:55.000 api = client.publisher_api
16:54:55.000 File "/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub/client.py", line 88, in publisher_api
16:54:55.000 generated = make_gax_publisher_api(self._connection)
16:54:55.000 File "/usr/local/lib/python2.7/dist-packages/google/cloud/pubsub/_gax.py", line 535, in make_gax_publisher_api
16:54:55.000 return PublisherClient(channel=channel)
16:54:55.000 File "/usr/local/lib/python2.7/dist-packages/google/cloud/gapic/pubsub/v1/publisher_client.py", line 188, in init
16:54:55.000 page_descriptors=self._PAGE_DESCRIPTORS)
16:54:55.000 File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 361, in construct_settings
16:54:55.000 bundler = _construct_bundling(bundling_config, bundle_descriptor)
16:54:55.000 File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 115, in _construct_bundling
16:54:55.000 bundler = gax.bundling.Executor(gax.BundleOptions(
16:54:55.000 AttributeError: 'module' object has no attribute 'bundling'

btw, the last release referenced on github is 0.14.1 !? what is 0.15.5 ?

**Comment by szymongluchowski** [comment]
Hi, I encountered the same issue, since last weekend I am not able to deploy pubsub worker.

**Comment by ensonic** [comment]
Me too.

**Comment by szymongluchowski** [comment]
Thanks for posting this workaround,  adding previous version of google-gax to requirements.txt helped. Anyway something is wrong with latest.

**Comment by szymongluchowski** [comment]
Seems to be fixed in 0.15.6.

**Comment by lukesneeringer** [comment]
Fixed in 0.15.6+
