### ISSUE TITLE
Bundling - how should the value of message byte size be computed ?

### ISSUE THREAD

**Issue by tbetbetbe** [googleapis/gax-python#18]
As of #17, a gax-python has a naive implementation that just uses str(...) to compute a length of the message field.

This is incorrect, it'd be more correct to coerce the message field to a bytearray and take the length of that.   Before correcting it, it'd be useful to establish if the bytesize checked by the threshold refers to the overall aggregate message size or just the total size of the repeated bundled fields.

**Comment by geigerj** [comment]
This question has been settled: we should sum the bytearray lengths of the bundled fields, rather than computing the aggregate message size, and add a 10% buffer to account for the possible difference between these values. It remains to correct the naive implementation.
