### ISSUE TITLE
'CallSettings.merge' blows away its own 'kwargs["metadata"]'

### ISSUE THREAD

**Issue by tseaver** [googleapis/gax-python#198]
From: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3123

If both `self.kwargs` and `options.kwargs` contain the `metadata` key, but with separate header names, the values need to be merged, rather than having `options.kwargs['metadata']` *replace* `self.kwargs['metadata']`.

**Comment by bjwatson** [comment]
@vam-google Sounds like this was fixed by https://github.com/googleapis/gax-python/pull/193. Does that fit your understanding?

**Comment by tseaver** [comment]
Yes, #193 looks like exactly the fix I was hoping for.  When will it be released?

(On another note, the tags in the repository don't seem to be complete for all releases).
