### ISSUE TITLE
PathTemplate.instantiate should be renamed

### ISSUE THREAD

**Issue by dhermes** [googleapis/gax-python#56]
See [discussion][1].

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/pull/1629#discussion_r56681876

**Comment by tbetbetbe** [comment]
A number of alternatives have been suggested:

> render is pretty standard for Python templating engines.

or

> fill or execute would be more descriptive.

However, please note that once the context of the class is understood, the current method name seems less awkward:

> instantiate usually means "create an instance of a class". I suppose that kind of makes sense in this case, but it's the wrong context.

**Comment by dhermes** [comment]
Seems less awkward to some. Still very awkward to me (and likely other Python devs). `instantiate == __init__` and that is decidedly different than `instance.foo(bar)`

**Comment by tbetbetbe** [comment]
I think we should change this.  Rationale:
- it's not that big change
- we'll have this same discussion in ruby and node.js which have mimicked this, if we change it here now and can agree on something works across these languages, it could cut the review time in those languages.

Let's rename this:  I think

`s/instantiate/render/`

is ok, and works in multiple languages
@jgeiger, @jmuk, @bjwatson: What do you think ?

**Comment by geigerj** [comment]
Sounds good to me

**Comment by garrettjonesgoogle** [comment]
Another option is 'format', drawing a parallel with:

* C: printf
* Java: String.format
* Go: Formatter

**Comment by jmuk** [comment]
SGTM++
For render vs format -- well, I have no idea. Both would work fine. I think many template engines use 'render', but several template engines use different verbs.

**Comment by tbetbetbe** [comment]
I think both format and render are fine.  Let's stick with render as that's what @dhermes has suggested.

**Comment by tbetbetbe** [comment]
This was fixed in #93
