### ISSUE TITLE
Switch generated code to using Google-style doc-strings

### ISSUE THREAD

**Issue by tbetbetbe** [googleapis/gax-python#63]
At the moment, the generated code uses raw sphinx directives.
[Google-style docstrings](http://www.sphinx-doc.org/en/stable/ext/example_google.html) are easier to maintain.

**Comment by tbetbetbe** [comment]
As part of this change, ensure that the return value is correctly specified.

**Comment by geigerj** [comment]
Fixed in the code generator.
