### ISSUE TITLE
gax api should configurably provide namedtuple or json analogues of the protobuf messages

### ISSUE THREAD

**Issue by tbetbetbe** [googleapis/gax-python#66]
- messages.py will soon be part of the vgened python code
- initially it will just extend the protobuf messages, and provide docstrings that document all the properties
  and the message itself

Proposal: 
update the individual messages classes so that behave like namedtuples by default, and remove clutter from the protobuf message.  This provides a much more usable return object to vgen api calls.

Implementation Details:
We might do this with a metaclass, or with code-gen if that's simple.
CallOptions would be updated to have a flag indicating what type of response should be returned

**Comment by tbetbetbe** [comment]
> messages.py will soon be part of the vgened python code

FYI: We ended up using a different approach to generated the docs that did not involve creating a messages.py

> Proposal: 
update the individual messages classes so that behave like namedtuples by default, and remove clutter from the protobuf message. This provides a much more usable return object to vgen api calls.

This should now be:
Proposal:
Make it possible for the return values from making api calls to be namedtuples with the same data  that is present in the protobuf objects.

**Comment by tbetbetbe** [comment]
Supporting this as namedtuples could be quite involved, but json could be a lot simpler

It should be possible to
- have a flag on CallOptions: `as_json_dict` that defaults to `False`
- when set to `true`, the result would be the python dictionary from of the json object

This would simplify integration with wrapping layers like gcloud-python.   This is possible now, but is a bit awkward because the protobuf's to json returns a string.  That issue being tracked in https://github.com/google/protobuf/issues/1351.

@tseaver, @jjg, @jmuk, @bjwatson, @dhermes

**Comment by geigerj** [comment]
Closing as obsolete.
