### ISSUE TITLE
Generator documents oneofs, maps, or nested enums incorrectly

### ISSUE THREAD

**Issue by saicheems** [googleapis/gax-python#68]
oneof renders as `null`
map renders as `list[value type]`
an enum nested inside a message may render incorrectly `enum.value` vs `message_name.enum.value`

**Comment by bjwatson** [comment]
Please verify whether these are still problems

**Comment by geigerj** [comment]
Currently,

- We render a field for each element of a oneof in the docs. We should probably additionally note that the fields in the oneof are mutually incompatible, but the representation as attributes is at least correct. Follow-up issue: https://github.com/googleapis/toolkit/issues/274
- [map is documented as dict](https://github.com/googleapis/toolkit/blob/08b03dcbae8fc2459675269d2bae20ea4aa6557e/src/test/java/com/google/api/codegen/testdata/python_message_library.baseline#L587)
- [nested enum is rendered incorrectly](https://github.com/googleapis/toolkit/blob/08b03dcbae8fc2459675269d2bae20ea4aa6557e/src/test/java/com/google/api/codegen/testdata/python_message_library.baseline#L569) -- it has should be `module.enum`, not `module.message.enum`. Follow-up issue: https://github.com/googleapis/toolkit/issues/275

**Comment by geigerj** [comment]
Closing this as obsolete; let's track the issues with oneof and enums separately in the issues referred to above.
