### ISSUE TITLE
Generator can't document nested messages

### ISSUE THREAD

**Issue by saicheems** [googleapis/gax-python#75]

**Comment by bjwatson** [comment]
@geigerj Please verify whether this is still an issue.

**Comment by geigerj** [comment]
This issue appears to be obsolete.

We have nested messages in the library baseline test: [SomeMessage and SomeMessage2](https://github.com/googleapis/toolkit/blob/08b03dcbae8fc2459675269d2bae20ea4aa6557e/src/test/java/com/google/api/codegen/testdata/library.proto#L165)

These appear to be documented correctly in the test result [here](https://github.com/googleapis/toolkit/blob/08b03dcbae8fc2459675269d2bae20ea4aa6557e/src/test/java/com/google/api/codegen/testdata/python_message_library.baseline#L594).
