### ISSUE TITLE
Informal Usability Bug Bash: Installation on linux is slow

### ISSUE THREAD

**Issue by vsubramani** [googleapis/gax-python#87]
Installation on linux is slow - both with and without virtual environments

**Comment by tbetbetbe** [comment]
To be clear: this was observed behaviour on one developer's machine, and there strong indications that the machine has poor network connectivity, as loading other sites (like the doc site) seemed slow as well.
 
Before attempting any kind of resolution, I recommend that we get several members of the team to try independently try installing on linux, and update this bug.

**Comment by tbetbetbe** [comment]
This is increasingly looking like it was an isolated networking issue.
Leaving for @vsubramani to close

**Comment by tbetbetbe** [comment]
Closing this.  We've confirmed that this was isolated to a single users' machine.
