### ISSUE TITLE
Informal Usability Bug Bash: Update project names in examples

### ISSUE THREAD

**Issue by vsubramani** [googleapis/gax-python#89]
Update all example values for project names to be domain-less ‘my-project’ and not ‘google.com:my-project’

**Comment by tbetbetbe** [comment]
FYI: this refers to the [generated docs for gax-pubsub](http://pythonhosted.org/gax-google-pubsub-v1/)

**Comment by tbetbetbe** [comment]
Fixed.
Example: the method docs for [create_topic](http://pythonhosted.org/gax-google-pubsub-v1/google.pubsub.v1.publisher_api.html#google.pubsub.v1.publisher_api.PublisherApi.create_topic) or [create_subscription](http://pythonhosted.org/gax-google-pubsub-v1/google.pubsub.v1.subscriber_api.html#google.pubsub.v1.subscriber_api.SubscriberApi.create_subscription)

**Comment by tbetbetbe** [comment]
@vsubramani PTAL, then LGTM and close the issue if it's OK

**Comment by tbetbetbe** [comment]
Closing the fix has been used in usability testing.
