### ISSUE TITLE
Informal Usability Bug Bash: Include protobuf import in all examples

### ISSUE THREAD

**Issue by vsubramani** [googleapis/gax-python#90]
Make all samples self contained to include the import for pubsub pb2

**Comment by tbetbetbe** [comment]
FYI: this refers to the [generated docs for gax-pubsub](http://pythonhosted.org/gax-google-pubsub-v1/)

**Comment by tbetbetbe** [comment]
Fixed.  There were two method comments that were affected, and both have been resolved

[publish](http://pythonhosted.org/gax-google-pubsub-v1/google.pubsub.v1.publisher_api.html#google.pubsub.v1.publisher_api.PublisherApi.publish)
[modify_push_config](http://pythonhosted.org/gax-google-pubsub-v1/google.pubsub.v1.subscriber_api.html#google.pubsub.v1.subscriber_api.SubscriberApi.modify_push_config)

@vsubramani, PTAL
LGTM if that's OK and close the issue.

**Comment by tbetbetbe** [comment]
This was fixed, and the docs for the publish method was successfully used by a number of users.
